### ISSUE TITLE
zypper already running

### ISSUE THREAD

**Issue by mgaulton** [RKrahl/auto-patch#2]
Thought you might want to see this. If zypper is already running, you will get exit 7 from it.
Was thinking a wait loop to attempt might get around that.

server6:/opt/auto-patch # /usr/sbin/auto-patch.py
Traceback (most recent call last):
  File "/usr/sbin/auto-patch.py", line 88, in <module>
    if patch(stdout=tmpf):
  File "/usr/sbin/auto-patch.py", line 67, in patch
    if Zypper.patch_check(stdout=stdout) == 0:
  File "/usr/sbin/auto-patch.py", line 41, in patch_check
    return cls.call(args, stdout=stdout, retcodes={100, 101})
  File "/usr/sbin/auto-patch.py", line 31, in call
    proc.check_returncode()
  File "/usr/lib64/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/bin/zypper', '--quiet', '--non-interactive', 'patch-check']' returned non-zero exit status 7.

**Comment by RKrahl** [comment]
Thanks for raising this issue! You're right, this case should be properly handled.
